#! Trying to put samtools and fusera in a single container

#######################################################
#                                                     #
#         Installing samtools and htslib              #
#                                                     #
#######################################################

FROM ubuntu:16.04

MAINTAINER Todd Pihl @ FNLCR todd.pihl@nih.gov

#htslib pull
#ENV VERSIONH 1.9
ENV VERSIONH 1.10.2
ENV NAMEH htslib
ENV URLH "https://github.com/samtools/${NAMEH}/releases/download/${VERSIONH}/${NAMEH}-${VERSIONH}.tar.bz2"

#samtools pull
#ENV VERSIONS 1.9
ENV VERSIONS 1.10
ENV NAMES samtools
ENV URLS "https://github.com/samtools/${NAMES}/releases/download/${VERSIONS}/${NAMES}-${VERSIONS}.tar.bz2"

#bcftools pull
ENV VERSIONB 1.10.2
ENV NAMEB bcftools
ENV URLB "https://github.com/samtools/${NAMEB}/releases/download/${VERSIONB}/${NAMEB}-${VERSIONB}.tar.bz2"

#Add required libraries
RUN apt-get update
RUN apt-get -y install \
  build-essential \
  zlib1g-dev \
  libncurses5-dev \
  libbz2-dev \
  liblzma-dev \
  libcurl4-openssl-dev \
  libssl-dev \
  libfuse-dev \
  fuse

#htslib build
WORKDIR /
ADD ${URLH} /

RUN tar xvjf ${NAMEH}-${VERSIONH}.tar.bz2
WORKDIR ${NAMEH}-${VERSIONH}
RUN pwd
RUN ./configure
RUN make
RUN make install
WORKDIR /

#samtools build
ADD ${URLS} /
RUN tar xvjf ${NAMES}-${VERSIONS}.tar.bz2
WORKDIR ${NAMES}-${VERSIONS}
RUN ./configure
RUN make
RUN make install
WORKDIR /

#bcftools build
ADD ${URLB} /
RUN tar xvjf ${NAMEB}-${VERSIONB}.tar.bz2
WORKDIR ${NAMEB}-${VERSIONB}
RUN ./configure
RUN make
RUN make install
WORKDIR /

#####################################################
#                                                   #
#         Installing Picard                         #
#                                                   #
#####################################################
ENV PICARD "https://github.com/broadinstitute/picard/releases/download/2.21.6/picard.jar"
RUN mkdir -p /picard
WORKDiR /picard
ADD ${PICARD} .
WORKDIR /

###################################################
#                                                 #
#         Set up the rest                         #
#                                                 #
###################################################

#/data is the data mountpoint.  Mounted as part of workflow
#/results is directory where samtools saves files.  Mount to VM directory for saved data
VOLUME ["/data", "/results"]
